import { test, expect } from "@playwright/test";

test.describe("Finding different elements using Playwright 1.20.0 codegen", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/practice/simple-elements.html");
  });

  test("Test page with IDs generated by codegen", async ({ page }) => {
    // steps:
    await page.goto("http://localhost:3000/practice/simple-elements.html");

    await page.locator('[data-testid="dti-label-element"]').click();
    await page.locator('[data-testid="dti-button-element"]').click();
    await page.locator('[data-testid="dti-checkbox"]').check();
    await page.locator('[data-testid="dti-input"]').click();
    await page.locator('[data-testid="dti-input"]').fill("test input");
    await page.locator('[data-testid="dti-input"]').press("Enter");
    await page.locator('[data-testid="dti-textarea"]').click();
    await page.locator('[data-testid="dti-textarea"]').fill("test area");
    await page.locator('[data-testid="dti-dropdown"]').selectOption("option2");
    await page.locator('[data-testid="dti-radio1"]').check();
    await page.locator('[data-testid="dti-radio2"]').check();
    await page.locator('[data-testid="dti-radio3"]').check();
    await page.locator('[data-testid="dti-range"]').click();
  });

  test("Test page with no IDs generated by codegen", async ({ page }) => {
    // steps:
    await page.goto(
      "http://localhost:3000/practice/simple-elements-no-ids.html"
    );

    await page.locator("text=Some text for label").click();
    await page.locator("text=Click me!").click();
    await page.locator('input[type="checkbox"]').check();
    await page.locator('input[type="text"]').click();
    await page.locator('input[type="text"]').fill("test input");
    await page.locator('input[type="text"]').press("Enter");
    await page.locator("textarea").click();
    await page.locator("textarea").fill("test area");
    await page.locator('select[name="name-dropdown"]').selectOption("option2");
    await page.locator('input[name="name-radio"]').first().check();
    await page.locator('input[name="name-radio"]').nth(1).check();
    await page.locator('input[name="name-radio"]').nth(2).check();
    await page.locator('input[type="range"]').click();
  });
});
